"""Added copy fields to Book model

Revision ID: 31ad5557a734
Revises: c882305c1f33
Create Date: 2023-11-29 03:43:45.580386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ad5557a734'
down_revision = 'c882305c1f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_copies', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_copies', sa.Integer(), nullable=True))
        batch_op.drop_column('copies')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('copies', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_copies')
        batch_op.drop_column('available_copies')

    # ### end Alembic commands ###
